name: Log Source Parameter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [log-source]

permissions:
  contents: write

jobs:
  log-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Git Pull
        run: git pull origin main
        
      - name: Log Source Parameter
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          echo "${{ github.event.client_payload.source }}" >> source-log.txt
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add source-log.txt
          git commit -m "Log source parameter: ${{ github.event.client_payload.source }}"
          git push
