name: Log Source Parameter

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source parameter'
        required: true
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  log-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Log Source Parameter
        run: |
          echo "Source: ${{ github.event.inputs.source }}" >> source-log.txt
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add source-log.txt
          git commit -m "Log source parameter: ${{ github.event.inputs.source }}"
          git push
